-- Migration 0009 — Plans, entitlements, usage thresholds, platform audit (M2.1)
--
-- Adds the data-model foundation for Milestone 2 of the StudioFlow
-- multi-agency build (docs/m2-multi-agency/PLAN.md). Five new tables
-- land in this migration:
--
--   1. platform_plan_template          — the 4 seeded plan tiers
--      (Starter / Growth / Enterprise / Custom). default_limits is a
--      JSONB blob of the documented limit shape; NULL for Custom.
--
--   2. agency_entitlement              — one row per agency. Holds the
--      plan choice + per-agency overrides + hard_stop_percent +
--      grace_policy. PK is agency_id, FK to platform_plan_template.
--
--   3. agency_entitlement_change       — APPEND-ONLY audit log of every
--      entitlement mutation. before / after are full snapshots of the
--      entitlement row. Triggers forbid UPDATE / DELETE.
--
--   4. agency_usage_threshold_event    — emitted by the usage-tracking
--      service (M2.3) when a counter crosses 80% / 90% / 100%.
--      UNIQUE (agency_id, resource, level) dedupes per-level events.
--
--   5. platform_audit_event            — APPEND-ONLY platform-level
--      audit log for every platform-admin action. Triggers forbid
--      UPDATE / DELETE.
--
-- Two enums:
--
--   agency_entitlement_grace_policy   — 'block' | 'allow_grace'
--   agency_usage_threshold_level      — 'warning' | 'urgent' | 'over_limit'
--
-- Append-only enforcement:
--
--   The two audit tables are made append-only via BEFORE UPDATE / BEFORE
--   DELETE triggers that RAISE EXCEPTION. The triggers are the single
--   source of truth — there is no separate GRANT to revoke (the app
--   uses one DB role for everything, see PORT_NOTES.md). The trigger
--   function is `forbid_modify_audit_log()`; it is re-usable for
--   future append-only tables (M2.7's platform_audit_event extensions
--   will use the same pattern).
--
-- Seed:
--
--   The 4 plan templates are seeded by this migration so the platform
--   console (M2.5+) has something to bind to. The seed is idempotent
--   (`ON CONFLICT (slug) WHERE archived_at IS NULL DO NOTHING`) so a
--   re-run after a partial failure is safe; it does not overwrite
--   edits made by an operator via the database console.
--
--   The default limits use the same key set the M2.2 service layer
--   expects (see schema/plans.ts comment block for the contract). The
--   Custom plan is the only one with NULL default_limits — it is a
--   sentinel meaning "no defaults; the agency must override every
--   limit at entitlement time."
--
-- Rollback:
--
--   DROP TABLE IF EXISTS platform_audit_event, agency_usage_threshold_event,
--     agency_entitlement_change, agency_entitlement, platform_plan_template
--     CASCADE;
--   DROP TYPE IF EXISTS agency_usage_threshold_level, agency_entitlement_grace_policy;
--   -- The trigger function is dropped automatically by CASCADE on the
--   -- tables that reference it; if any future table re-uses it, drop
--   -- it explicitly: DROP FUNCTION IF EXISTS forbid_modify_audit_log();
--
-- Note on a pre-existing schema/DB mismatch:
--
--   The brand_voice_workspace_archived_idx index was hand-added by
--   migration 0006 but is not declared in the Drizzle schema
--   (src/lib/db/schema/brand-kit.ts). Drizzle-kit's auto-diff
--   suggested dropping it; we explicitly keep it because the drop
--   would be an unrelated destructive change in an M2.1 migration
--   and the Drizzle schema mismatch is a pre-existing M1 issue.
--   Follow-up: align the Drizzle schema with the DB (either add
--   the index to brand-kit.ts or accept the drop in a separate
--   M1.10+ cleanup commit).

-- ─── DDL (generated by drizzle-kit) ────────────────────────────────────────
CREATE TYPE "public"."agency_entitlement_grace_policy" AS ENUM('block', 'allow_grace');--> statement-breakpoint
CREATE TYPE "public"."agency_usage_threshold_level" AS ENUM('warning', 'urgent', 'over_limit');--> statement-breakpoint
CREATE TABLE "agency_entitlement_change" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"actor_user_id" uuid,
	"before" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"after" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agency_entitlement" (
	"agency_id" uuid PRIMARY KEY NOT NULL,
	"plan_template_id" uuid NOT NULL,
	"overrides" jsonb,
	"hard_stop_percent" numeric(5, 2) DEFAULT '100' NOT NULL,
	"grace_policy" "agency_entitlement_grace_policy",
	"effective_since" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agency_entitlement_hard_stop_range" CHECK ("agency_entitlement"."hard_stop_percent" >= 0),
	CONSTRAINT "agency_entitlement_hard_stop_max" CHECK ("agency_entitlement"."hard_stop_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "agency_usage_threshold_event" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"resource" text NOT NULL,
	"percent" numeric(7, 2) NOT NULL,
	"level" "agency_usage_threshold_level" NOT NULL,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agency_usage_threshold_event_percent_nonneg" CHECK ("agency_usage_threshold_event"."percent" >= 0)
);
--> statement-breakpoint
CREATE TABLE "platform_audit_event" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_user_id" uuid,
	"action" text NOT NULL,
	"target" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"ip" "inet",
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_plan_template" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"default_limits" jsonb,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agency_entitlement_change" ADD CONSTRAINT "agency_entitlement_change_agency_id_agency_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agency"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_entitlement_change" ADD CONSTRAINT "agency_entitlement_change_actor_user_id_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_entitlement" ADD CONSTRAINT "agency_entitlement_agency_id_agency_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agency"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_entitlement" ADD CONSTRAINT "agency_entitlement_plan_template_id_platform_plan_template_id_fk" FOREIGN KEY ("plan_template_id") REFERENCES "public"."platform_plan_template"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_usage_threshold_event" ADD CONSTRAINT "agency_usage_threshold_event_agency_id_agency_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agency"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_audit_event" ADD CONSTRAINT "platform_audit_event_actor_user_id_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agency_entitlement_change_agency_idx" ON "agency_entitlement_change" USING btree ("agency_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX "agency_entitlement_change_actor_idx" ON "agency_entitlement_change" USING btree ("actor_user_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX "agency_entitlement_plan_template_idx" ON "agency_entitlement" USING btree ("plan_template_id");--> statement-breakpoint
CREATE UNIQUE INDEX "agency_usage_threshold_event_dedupe_idx" ON "agency_usage_threshold_event" USING btree ("agency_id","resource","level");--> statement-breakpoint
CREATE INDEX "agency_usage_threshold_event_agency_resource_idx" ON "agency_usage_threshold_event" USING btree ("agency_id","resource","observed_at" DESC);--> statement-breakpoint
CREATE INDEX "platform_audit_event_actor_idx" ON "platform_audit_event" USING btree ("actor_user_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX "platform_audit_event_action_idx" ON "platform_audit_event" USING btree ("action","created_at" DESC);--> statement-breakpoint
CREATE INDEX "platform_audit_event_target_idx" ON "platform_audit_event" USING btree (("target" ->> 'type'),("target" ->> 'id'),"created_at" DESC);--> statement-breakpoint
CREATE UNIQUE INDEX "platform_plan_template_slug_unique" ON "platform_plan_template" USING btree ("slug") WHERE archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "platform_plan_template_archived_at_idx" ON "platform_plan_template" USING btree ("archived_at");

-- ─── Append-only enforcement (hand-written) ────────────────────────────────
--
-- Single trigger function for both append-only tables. The function
-- raises an exception that names the offending table so the
-- application sees a clear message instead of a generic constraint
-- violation.
--
-- We use the trigger (vs. REVOKE UPDATE/DELETE on the app role)
-- because the entire application connects with a single DB role
-- (see PORT_NOTES.md — Supabase → plain Postgres sidecar). The
-- trigger is the structural enforcement that does not depend on
-- role-based separation.
CREATE OR REPLACE FUNCTION forbid_modify_audit_log() RETURNS TRIGGER AS $$
DECLARE
  tbl text := TG_TABLE_NAME;
  trg text := TG_NAME;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    RAISE EXCEPTION
      'append-only table % forbids UPDATE (trigger %, row id=%)',
      tbl, trg, COALESCE(OLD.id::text, '<unknown>')
      USING ERRCODE = 'insufficient_privilege';
  ELSIF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'append-only table % forbids DELETE (trigger %, row id=%)',
      tbl, trg, COALESCE(OLD.id::text, '<unknown>')
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

DROP TRIGGER IF EXISTS agency_entitlement_change_no_update ON agency_entitlement_change;--> statement-breakpoint
CREATE TRIGGER agency_entitlement_change_no_update
  BEFORE UPDATE OR DELETE ON agency_entitlement_change
  FOR EACH ROW EXECUTE FUNCTION forbid_modify_audit_log();
--> statement-breakpoint
DROP TRIGGER IF EXISTS platform_audit_event_no_update ON platform_audit_event;--> statement-breakpoint
CREATE TRIGGER platform_audit_event_no_update
  BEFORE UPDATE OR DELETE ON platform_audit_event
  FOR EACH ROW EXECUTE FUNCTION forbid_modify_audit_log();

-- ─── Seed: 4 plan templates ────────────────────────────────────────────────
--
-- The default limits use the documented key set:
--   workspaces, users, total_social_profiles, social_profiles_per_platform,
--   storage_bytes, monthly_ai_requests, monthly_ai_input_tokens,
--   monthly_ai_output_tokens, daily_ai_requests_per_user,
--   max_output_tokens_per_request, enabled_capabilities.
--
-- The Custom plan is a sentinel with NULL default_limits — it means
-- "no defaults; the agency must override every limit at entitlement
-- time". The service layer (M2.2) is responsible for not crashing on
-- a NULL here.
--
-- ON CONFLICT (slug) WHERE archived_at IS NULL DO NOTHING keeps the
-- seed idempotent: re-runs after a partial failure will not overwrite
-- operator edits to the non-unique columns (name, description,
-- default_limits) on the existing row. Soft-archived rows are ignored
-- so a re-activated plan does not collide with the active one.
INSERT INTO "platform_plan_template" ("slug", "name", "description", "default_limits") VALUES
  (
    'starter',
    'Starter',
    'For small agencies and solo operators. 1 workspace, 3 users, 5 connected profiles.',
    '{
      "workspaces": 1,
      "users": 3,
      "total_social_profiles": 5,
      "social_profiles_per_platform": 1,
      "storage_bytes": 5368709120,
      "monthly_ai_requests": 100,
      "monthly_ai_input_tokens": 100000,
      "monthly_ai_output_tokens": 50000,
      "daily_ai_requests_per_user": 20,
      "max_output_tokens_per_request": 2000,
      "enabled_capabilities": [
        "campaign_ideas",
        "brief_improvement",
        "caption_drafts",
        "platform_adaptation",
        "related_format_ideas",
        "completeness_check"
      ]
    }'::jsonb
  ),
  (
    'growth',
    'Growth',
    'For agencies scaling their client portfolio. 5 workspaces, 15 users, 25 connected profiles.',
    '{
      "workspaces": 5,
      "users": 15,
      "total_social_profiles": 25,
      "social_profiles_per_platform": 3,
      "storage_bytes": 53687091200,
      "monthly_ai_requests": 1000,
      "monthly_ai_input_tokens": 1000000,
      "monthly_ai_output_tokens": 500000,
      "daily_ai_requests_per_user": 50,
      "max_output_tokens_per_request": 4000,
      "enabled_capabilities": [
        "campaign_ideas",
        "brief_improvement",
        "caption_drafts",
        "platform_adaptation",
        "related_format_ideas",
        "completeness_check"
      ]
    }'::jsonb
  ),
  (
    'enterprise',
    'Enterprise',
    'For large agencies and brand teams. 50 workspaces, 200 users, 250 connected profiles.',
    '{
      "workspaces": 50,
      "users": 200,
      "total_social_profiles": 250,
      "social_profiles_per_platform": 20,
      "storage_bytes": 536870912000,
      "monthly_ai_requests": 10000,
      "monthly_ai_input_tokens": 10000000,
      "monthly_ai_output_tokens": 5000000,
      "daily_ai_requests_per_user": 200,
      "max_output_tokens_per_request": 8000,
      "enabled_capabilities": [
        "campaign_ideas",
        "brief_improvement",
        "caption_drafts",
        "platform_adaptation",
        "related_format_ideas",
        "completeness_check"
      ]
    }'::jsonb
  ),
  (
    'custom',
    'Custom',
    'No defaults — every limit is set per-agency at entitlement time.',
    NULL
  )
ON CONFLICT (slug) WHERE archived_at IS NULL DO NOTHING;
