-- Migration 0026 — `activity_kind` enum gains `delete` + `bulk_delete`
-- (FEAT-DELETE-ACTIVITY-LOG-2026-09-02).
--
-- Plan §1: per-idea and bulk-idea resets now write an
-- `activity_event` row in the same transaction as the DELETE.
-- The `kind` column is `text` on disk (see
-- `src/lib/db/schema/notifications.ts`) but the Drizzle-side
-- type is the `activity_kind` ENUM, so adding the new values
-- here keeps the schema-as-code and the storage shape in
-- sync. Two `ALTER TYPE … ADD VALUE` statements, both wrapped
-- with `IF NOT EXISTS` so the migration is safely
-- re-runnable in the same way as migration 0021.
--
-- No data backfill: the ENUM is a type, not a row constraint.
-- Existing activity_event rows continue to be valid; new
-- rows from `resetIdeaAction` / `resetAllIdeasAction` use
-- the new values.
--
-- The Drizzle snapshot in `meta/0026_snapshot.json` is
-- regenerated by `pnpm db:generate`; the journal entry is
-- registered in `meta/_journal.json`.

ALTER TYPE "public"."activity_kind" ADD VALUE IF NOT EXISTS 'delete';--> statement-breakpoint
ALTER TYPE "public"."activity_kind" ADD VALUE IF NOT EXISTS 'bulk_delete';
