import { NextResponse, type NextRequest } from "next/server";

/**
 * PR 2 / Tier 2 (perf/media): preview-variant route.
 *
 * Companion to `/api/media/assets/[id]`. Where the original route
 * streams the full-resolution bytes, this route serves the 480px WebP
 * variant generated by `src/lib/media/thumbnails.ts`. The media grid,
 * gallery strip, and planning-preview `<img>` all prefer this URL
 * when the asset has a preview (`media_assets.preview_storage_object_id`
 * is set). When it isn't, the components fall back to the full URL.
 *
 * Cache policy:
 *   - Cache-Control: `private, max-age=86400, immutable`
 *     The preview is content-addressed by its underlying storage_object
 *     id. A change to the original asset creates a new preview row, so
 *     the variant never mutates in place. `immutable` tells the browser
 *     not to revalidate, which is the correct semantics.
 *   - Vary: Cookie
 *     Same justification as the full route: per-user cache so role
 *     changes invalidate the bytes within the 24h window.
 *
 * Auth: same as the full route — a non-owner with no membership on
 * the asset's agency gets a 404 (same shape as the asset's own
 * visibility check). We do NOT distinguish "no preview" from "no
 * access" externally; both surface as 404 to avoid leaking the
 * existence of a preview variant to a user who couldn't read the
 * original.
 *
 * Errors:
 *   - 401 when no session
 *   - 404 when no asset, asset not ready, asset has no preview, or
 *     the caller can't read the asset
 *   - 502 when R2 returns non-2xx (the body is short and stable)
 *   - 500 on any other server-side failure
 */
import { auth } from "@/lib/auth/config";
import { currentActor } from "@/lib/auth/current-actor";
import { fetchPreviewForActor } from "@/lib/media/thumbnails";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  // Either auth path is valid; prefer session.userId (the cheaper
  // path) and fall back to currentActor() for the auth-action code
  // path that issues short-lived tokens.
  const session = await auth();
  const actor = session?.user?.id ? { id: session.user.id } : await currentActor();
  if (!actor) return NextResponse.json({ error: "Not signed in" }, { status: 401 });

  const { id } = await params;
  const preview = await fetchPreviewForActor(actor, id);
  if (!preview) {
    return NextResponse.json({ error: "Media preview not found" }, { status: 404 });
  }

  // Pull the variant bytes via the same proxy path the full route
  // uses. We don't expose the storage_object id externally — the only
  // way to fetch a preview is through this route.
  const { fetchStorageObject } = await import("@/lib/storage/read-service");
  const remote = await fetchStorageObject({
    agencyId: preview.agencyId,
    workspaceId: preview.workspaceId,
    objectId: preview.objectId,
    expiresInSeconds: 300,
  });
  if (!remote) {
    return NextResponse.json({ error: "Media preview unavailable" }, { status: 502 });
  }

  const headers = new Headers({
    "Content-Type": preview.mimeType,
    "Cache-Control": "private, max-age=86400, immutable",
    Vary: "Cookie",
    "X-Content-Type-Options": "nosniff",
  });
  // Intrinsic dimensions live on the variant's storage_objects row;
  // emit them on the response so the browser can reserve layout space
  // before the bytes finish decoding. The components can read these
  // via `img.width` / `img.height` once the body arrives.
  if (typeof preview.width === "number" && preview.width > 0) {
    headers.set("X-Preview-Width", String(preview.width));
  }
  if (typeof preview.height === "number" && preview.height > 0) {
    headers.set("X-Preview-Height", String(preview.height));
  }
  for (const name of ["content-length", "etag", "last-modified", "accept-ranges"]) {
    const value = remote.headers.get(name);
    if (value) headers.set(name, value);
  }
  return new NextResponse(remote.body, { status: remote.status, headers });
}
